PRODUCT_PACKAGES += SuperUser
PRODUCT_PACKAGES += RkApkinstaller
PRODUCT_PACKAGES += ABenchMark
#PRODUCT_PACKAGES += NovaLauncher
PRODUCT_PACKAGES += ESFileExplorer
PRODUCT_PACKAGES += WifiAnalyzer
PRODUCT_PACKAGES += ViPER4Android_FX_A4.x
